# Generated by Django 3.0.2 on 2020-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
